@base_url=https://api.unsplash.com

### get photos
GET {{base_url}}/search/photos?query=cars
Authorization: Client-ID WRGiE_HcVaepfpCB33mme5TG-QsKcgW-XOxlPNlfH98


### get collection photos 
GET {{base_url}}/users/egor_vikhrev/photos
Authorization: Client-ID WRGiE_HcVaepfpCB33mme5TG-QsKcgW-XOxlPNlfH98

### list collections
GET {{base_url}}/collections
Authorization: Client-ID WRGiE_HcVaepfpCB33mme5TG-QsKcgW-XOxlPNlfH98